### ISSUE TITLE
pdf report and utf

### ISSUE THREAD

**Issue by Maasik** [bramley/phplist-plugin-common#13]
Need support for utf characters in pdf reports.
There is a version of fpdf with support utf: http://www.fpdf.org/en/script/script92.php

**Comment by bramley** [comment]
I did look at tFPDF when I was changing the reports to use FPDF. I will take another look at it.

**Comment by bramley** [comment]
I have created new branches of this plugin and the Message Statistics plugin that use tFPDF. Can you install those to try them out?

On the Manage Plugins page use these URLs to install the branches, which will replace the existing plugins

    https://github.com/bramley/phplist-plugin-common/archive/tfpdf.zip
    https://github.com/bramley/phplist-plugin-statistics/archive/tfpdf.zip

**Comment by Maasik** [comment]
Yes, now everything is correct with symbols!
Thank you.
It remains only to add localization support in file CampaignReport.php

`        $lines[] = ['Subject', $subject];
        $lines[] = ['Start date',  $fields['datestart']];
        $lines[] = ['End date', $fields['datesent']];
...
`

**Comment by bramley** [comment]
You can now translate the captions on the pdf report. 
First update the plugin. If you have not already done so, revert to using the master branch

    https://github.com/bramley/phplist-plugin-statistics/archive/master.zip

Copy the block of 10 lines from the lan/en.php file to your language file

```
//  Campaign pdf report
    'Title' => 'Title',
    'Start date' => 'Start date',
    'End date' => 'End date',
    'Delivered' => 'Delivered',
    'Not opened' => 'Not opened',
    'Users who clicked' => 'Users who clicked',
    'Total number of clicks' => 'Total number of clicks',
    'Users who forwarded' => 'Users who forwarded',
    'Of the total who opened' => 'Of the total who opened',

```
