### ISSUE TITLE
PHP 7.1 compat error

### ISSUE THREAD

**Issue by arius28** [bramley/phplist-plugin-common#14]
Hey @bramley,

After upgrading from 3.15.7 to 3.17.0 I get the following Composer error: 

> Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.4.0".

Obviously I am not running PHP 7.4, I am running PHP 7.1. What was the major change that caused the plugin to stop working in 7.1? Was it due to the emogrifier update or some other dependency update perhaps? Can this be remedied?

**Comment by bramley** [comment]
I don't know what it is referring to. But I don't understand what you are actually doing. What is the reason for running composer?

**Comment by bramley** [comment]
I can revert the upgrade to psr/container, as that was not deliberate.

**Comment by arius28** [comment]
To answer your original question, I was not running composer. I logged in to phplist (3.6.5), updated common plugin through the update button on the Manage plugins page. It said the update was successfull and when I clicked to go to the Manage plugins page again that is the error I received and it blocked all of phplist. I downgraded maually to 3.15.8 and it was working fine.

**Comment by arius28** [comment]
Just installed 3.18 using the master.zip. All is good, thank you!

**Comment by bramley** [comment]
I didn't realise that check on the php version was taking place. Thanks for reporting this!
