### ISSUE TITLE
PHPlist crashes after installing phplist-plugin-common

### ISSUE THREAD

**Issue by swakeel** [bramley/phplist-plugin-common#2]
I am running phpList ltd. - v3.0.12  
Installed several plugins from within the "Manage Plugins" page and they seem to work well. 
When I installed the Segment Plugin https://github.com/bramley/phplist-plugin-segment/archive/master.zip, got a confirmation, then clicked "continue" button, phplist wouldn't load at all. No newsletters page and no admin page.  
I had to use the cpanel file manager to remove the plugin folder and file.
went back into phplist and tried a couple of different statistics which worked, then one didn't:
I was trying "Bounced Domains" menu, and got the error "phplist-plugin-common must be installed and enabled to use this plugin".  Searched on google and found this page:  https://github.com/bramley/phplist-plugin-common  which specifies the plugin location as: https://github.com/bramley/phplist-plugin-common/archive/master.zip
Installed from the "Manage Plugins" menu, clicked "continue", got a blank page, wiated 10 seconds and clicked F5 and now it worked, I enabled the plugin.  Trying Bounced Domains again, got a blank page, then phplist wouldn't work at all.
Restarting firefox didn't help, and Chrome is showing the same behavior. 
Removed the Common plug-in using cpanel.

Thanks for helping.

**Comment by bramley** [comment]
It is not very clear which plugins you have installed and in which order. You also need to check that the plugins have been installed properly as described in the installation process.

**Comment by swakeel** [comment]
Sorry. I installed all of the plugins from within phplist, in this order, and enabled each one after install:

- TinyMCE Plugin HTML editor  https://github.com/bramley/phplist-plugin-tinymce/archive/master.zip
- Attribute Select   https://github.com/michield/phplist-plugin-attributeselect/archive/master.zip
- Bounce Statistics  https://github.com/bramley/phplist-plugin-bounces/archive/master.zip
- Manage Campaigns (extra commands) https://github.com/bramley/phplist-plugin-campaigns/archive/master.zip
- Listcleaner plugin http://github.com/michield/phplist-plugin-listcleaner/archive/master.zip
- Campaign Statistics  https://github.com/bramley/phplist-plugin-statistics/archive/master.zip
- Segment Plugin  https://github.com/bramley/phplist-plugin-segment/archive/master.zip
         Manually Removed 
- Phplist-plugin-common https://github.com/bramley/phplist-plugin-common/archive/master.zip
         Manually Removed

**Comment by michield** [comment]
I think we may need a plugin hierarchy system that loads some plugins before others. Not sure how to resolve that in the meantime

**Comment by bramley** [comment]
Each of my plugins has installation instructions that clearly explain the dependencies. It looks like you didn't follow those instructions if this is the order that you installed the plugins. 
Other than that I'm not really able to diagnose what is not working in your case.

**Comment by bramley** [comment]
When upgrading a phplist installation today I had a similar problem. The cause turned out to be the php version being used, php 5.2. This plugin requires a minimum of 5.3.

**Comment by swakeel** [comment]
Thanks for the update Duncan. I've checked phpinfo and found that we're using PHP Version 5.2.17. Will try to upgrade to 5.3 (if supported by our hosting) and try the Common and Segment plugins again.

**Comment by swakeel** [comment]
Update: upgraded hosting to PHP 5.3 and both plugins "Common" and "Segment"  work now!
