### ISSUE TITLE
php 8.2

### ISSUE THREAD

**Issue by michield** [bramley/phplist-plugin-common#20]
It seems emogrifier needs bumping to 7.0 to pass on PHP8.2

https://github.com/bramley/phplist-plugin-common/blob/master/composer.json#L24

https://github.com/phpList/phplist3/actions/runs/3867541447/jobs/6592386512#step:7:46

**Comment by bramley** [comment]
I have updated that package to 7.0, so please can you try again?

**Comment by michield** [comment]
Yes, that worked, thanks
