### ISSUE TITLE
Failure on system requirement phpList version 3.3.2 or later

### ISSUE THREAD

**Issue by luchris** [bramley/phplist-plugin-common#21]
I am on phpList 3.6.14. How do i enable Common plugin?

Thanks

**Comment by bramley** [comment]
What is the background to this? Is it a new installation, or an upgrade and the plugin used to be enabled? I guess that you have not installed or updated everything.
After logging-in, there is a version number at the bottom of each page, what value is that?

**Comment by luchris** [comment]
Hi, this is a fresh installation.

phpList version 3.6.14

**Comment by bramley** [comment]
I don't understand this. Can you try debugging it? In file `lists/admin/plugins/CommonPlugin.php`, add a line to display the phplist version in function `dependencyCheck`. Then just redisplay the phplist home page.

The value should be the same as displayed at the bottom of each page, in which case the version_compare test should pass.

```
    public function dependencyCheck()
    {
var_dump(VERSION);
        return [
            'PHP version 7 or greater' => version_compare(PHP_VERSION, '7') > 0,
            'phpList version 3.3.2 or later' => version_compare(VERSION, '3.3.2') >= 0,
        ];
    }
```

**Comment by luchris** [comment]
Added the above codes to admin/plugins/CommonPlugin.php and phpList dont load anymore.

The pageroot is ''

I am running phpList 3.6.14 on Apache 2.4.37 with PHP Version 8.3.0. Please see image attached


![CommonPlugin](https://github.com/bramley/phplist-plugin-common/assets/13183475/2087ab68-141a-483b-b437-db45e2bfcc01)

**Comment by luchris** [comment]
Sorry for the trouble. The version in https://github.com/phpList/phplist3/releases/tag/v3.6.14 is not 3..6.14. Instead this is a dev version. Re-install from https://sourceforge.net/projects/phplist/files/phplist/3.6.14/phplist-3.6.14.tgz/download and everything is fine. Thank you.
