### ISSUE TITLE
parse error

### ISSUE THREAD

**Issue by michield** [bramley/phplist-plugin-common#4]
I get PHP Parse error:  syntax error, unexpected 'List' (T_LIST), expecting identifier (T_STRING) in phplist-plugin-common/plugins/Common/DAO/List.php on line 23

I guess the word "list" is reserved. 

Is this going to cause problems?

**Comment by bramley** [comment]
Yes it will do. I have had a look but cannot see where that class is being used. Which other plugin were you using when the error was displayed?

**Comment by michield** [comment]
I found it when I ran a "lint" across the entire codebase. 

./scripts/lint.sh in the phpList root

**Comment by bramley** [comment]
Ah ok. That class is in a set of namespaced classes that are used currently only by the Content Areas plugin, but that particular class isn't used. The non-namespaced class has a name like CommonPlugin_DAO_List so that is not a problem.

I'll think about what to rename it to.
