### ISSUE TITLE
[Question] Compatibility with PHP v7.1

### ISSUE THREAD

**Issue by agustinaliagac** [bramley/phplist-plugin-common#7]
Hello ! Sorry, this is probably a stupid question since the README says "Requires php version 5.4 or later.", but I just need to be sure. Is this plugin fully compatible with PHP 7.1 ? 

I'm upgrading my server and it looks like phplist is having trouble importing/using it. 

Thanks !

**Comment by bramley** [comment]
There are no problems using the plugin on my shared hosting account that has php 7.1.

**Comment by agustinaliagac** [comment]
Thanks @bramley !
